index:
    path: /{name}
    controller: App\Controller\IndexController::home

homepage:
 path: /
 controller: App\Controller\IndexController::home

article_save:
  path: /article/save
  controller: App\Controller\IndexController::save
